# Site settings
author: Hyungjun Kang
title: Blog
header-img: img/home-bg.png
email: hyungjun.kang@yahoo.com
copyright_name: Hyungjun Kang
description: > # this means to ignore newlines until "baseurl:"
  Data Science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tyoon1016

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
